---
# requires installed module: libvirt-python

- hosts: all
  gather_facts: False
  serial: 1
  tasks:

  - name: prepare vms
    include_role:
      name: clonevm

  # test reboot
  # - name: test reboot
  #   ignore_errors: yes
  #   reboot:
  #     connect_timeout: 1
  #     reboot_timeout: 1